Cooptavanza.Wallet/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cooptavanza.Wallet.Controllers
{
    public class ServicesController : Controller
    {
        // GET: Services
        public ActionResult BankDeposit()
        {
            return View();
        }

        public ActionResult MoneyTransfer()
        {
            return View();
        }

        public ActionResult ChinaRemit()
        {
            return View();
        }

        public ActionResult Check21()
        {
            return View();
        }

        public ActionResult CreditCard()
        {
            return View();
        }

        public ActionResult EFT()
        {
            return View();
        }

        public ActionResult CashLocation()
        {
            return View();
        }

        public ActionResult CoopMember()
        {
            return View();
        }

        public ActionResult OCT()
        {
            return View();
        }

        public ActionResult WireTransfer()
        {
            return View();
        }

        public ActionResult PropertyCard()
        {
            return View();
        }

        public ActionResult TopupAirtime()
        {
            return View();
        }

        public ActionResult EmailTransfer()
        {
            return View();
        }

        public ActionResult SMSTransfer()
        {
            return View();
        }

        public ActionResult ContactUs()
        {
            return View();
        }
    }
}

Cooptavanza.Wallet/Controllers/SigninController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cooptavanza.Wallet.Controllers
{
    public class SigninController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
       
    }
}

Cooptavanza.Wallet/Views/Services/BankDeposit.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }
        <div id="landing-content">
            <div id="main-slider" class="carousel slide bg-dark" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#main-slider" data-slide-to="0" class="active"></li>
                    <li data-target="#main-slider" data-slide-to="1"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="item  active">
                        <img src="https://static.pexels.com/photos/265667/pexels-photo-265667.jpeg" alt="" class="img-background">
                        <div class="row">
                            <div class="col-xs-6 text-right">
                                <!--<img src="img/coop-card.jpg" alt="responsive" class="fadeInLeftLarge animation-delay6 m-top-lg m-bottom-lg">-->
                            </div>
                            <div class="col-xs-6">
                                <h2 style="" class="m-top-lg m-right-md text-white fadeInDownLarge animation-delay3 banner-font">Bank Deposit</h2>
                                <p style="" class="text-warning fadeInUpLarge animation-delay6 hidden-xs banner-color">
                                    Send Money any where in the world
                                </p>
                                <a href="@Url.Action(" Index", "Signin" )" class="btn btn-default btn-lg fadeInRightLarge animation-delay8">Login <i class="fa fa-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <img src="/Content/images/money_transfer_1.2.jpg" alt="" class="img-background">
                        <div class="row">
                            <div class="col-md-6 text-right">
                                <h2 style="" class="m-top-lg m-right-md text-white fadeInDownLarge animation-delay3 banner-font"><b>Bank Deposit</b></h2>
                                <p style="" class="text-white fadeInUpLarge animation-delay6 m-right-md hidden-xs banner-color">
                                    innovating online digital payment services <br />
                                    and revolutionizing ecommerce
                                </p>
                                <a href="index-2.html" class="btn btn-default btn-lg fadeInLeftLarge animation-delay8 m-bottom-lg m-right-md">Find Out More</a>
                            </div>
                        </div>
                    </div>
                </div>
                <a class="left carousel-control" href="#main-slider" data-slide="prev">
                    <span class="fa fa-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#main-slider" data-slide="next">
                    <span class="fa fa-chevron-right"></span>
                </a>
            </div>
            <div class="bg-white content-padding text-center font-lg">
                <div class="container">
                    <span class="m-right-lg"><h1><b>Bank Deposit</b></h1></span>
                    <div class="inline-block m-top-sm">
                        <p> Note: This is a sample paragraph only</p>
                        <p style="text-align:justify">
                            <small>
                                Today’s web-savvy customers require self-service banking access to automate recurring bill payments with the convenience and flexibility of making payments anytime and anywhere. With the Coop Red Direct Debit System (DDS), your members can easily and efficiently self-service all aspects of their accounts from anywhere in the world; 24/7 while remaining transparent.

                                The DDS system is a recurring bill payment system whereby service providers and businesses, that have joined the Coop Red Network, can enhance their debt collection and payment process. DDS allows your members to automatically pay bills directly from their account without writing a check or withdrawing cash. Additional, the system allows automatic payments to any business or service provider that has registered with the Coop Red Network. Your members are in full control over when their payments will be made, the amount of payments and all things related to the payment. It can be turned off at any time and then back on at the convenience of the member.

                                DDS also works with business and service providers not registered with the Coop Red Network provided your member has the required banking information for the business or service provider. The DDS system delivers a consistent bill payment experience.

                                DDS provides member merchants with rapid reductions in operational costs, quicker payment turnaround and enhanced customer service
                            </small>
                        </p>
                    </div>
                </div>
            </div>
            <div id="block-nodeblock-4" class="section-lg block block-nodeblock m-top7">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                            <div class="sec-titiel m-bottom5">
                                <h2 class="uppercase font-black font30 nomargin">Exclusive Services</h2>
                            </div>
                            <div class="col-md-12 m-bottom1 nopadding">
                                <div class="content-feature-col one">
                                    <div class="icon-box-col"> <span class="icon-layers"></span> </div>
                                    <div class="feature-icon-col left-padd10">
                                        <h2 class="font-black font20 uppercase m-bottom1">e-Mail Money</h2>
                                        <p>A secure and convenient way to send and receive money directly from one bank account to another.</p>
                                        <div class="title-line wide50 color m-top2"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12 m-bottom1 nopadding">
                                <div class="content-feature-col active one">
                                    <div class="icon-box-col"> <span class="icon-cup"></span> </div>
                                    <div class="feature-icon-col left-padd10">
                                        <h2 class="font-black font20 uppercase m-bottom1">Server to Server Money Transfer</h2>
                                        <p>Faster and cheaper than going through payment instructions via SWIFT.</p>
                                        <div class="title-line wide50 color m-top2"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12 m-bottom1 nopadding">
                                <div class="content-feature-col one">
                                    <div class="icon-box-col"> <span class="icon-call-out"></span> </div>
                                    <div class="feature-icon-col left-padd10">
                                        <h2 class="font-black font20 uppercase m-bottom1">Direct Debit/Deposit</h2>
                                        <p>Allow your customers to pay bills directly from their cooperative account or fund their account from any existing bank accounts..</p>
                                        <div class="title-line wide50 color m-top2"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6"> <img class="img-responsive" alt="" src="http://newdrupal.expertscabin.com/sites/default/files/new/index.png" data-anim-delay="100" data-anim-type="fade-in-left"> </div>
                    </div>
                </div>
            </div>
            <p>&nbsp;</p>
        </div><!-- /landing-content -->

Cooptavanza.Wallet/Views/Services/CashLocation.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }
        <div id="landing-content">
            <div id="main-slider" class="carousel slide bg-dark" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#main-slider" data-slide-to="0" class="active"></li>
                    <li data-target="#main-slider" data-slide-to="1"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="item  active">
                        <img src="https://static.pexels.com/photos/265667/pexels-photo-265667.jpeg" alt="" class="img-background">
                        <div class="row">
                            <div class="col-xs-6 text-right">
                                <!--<img src="img/coop-card.jpg" alt="responsive" class="fadeInLeftLarge animation-delay6 m-top-lg m-bottom-lg">-->
                            </div>
                            <div class="col-xs-6">
                                <h2 style="" class="m-top-lg m-right-md text-white fadeInDownLarge animation-delay3 banner-font">Cash Location</h2>
                                <p style="" class="text-warning fadeInUpLarge animation-delay6 hidden-xs banner-color">
                                    Send Money any where in the world
                                </p>
                                <a href="@Url.Action(" Index", "Signin" )" class="btn btn-default btn-lg fadeInRightLarge animation-delay8">Login <i class="fa fa-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <img src="/Content/images/money_transfer_1.2.jpg" alt="" class="img-background">
                        <div class="row">
                            <div class="col-md-6 text-right">
                                <h2 style="" class="m-top-lg m-right-md text-white fadeInDownLarge animation-delay3 banner-font"><b>Cash Location</b></h2>
                                <p style="" class="text-white fadeInUpLarge animation-delay6 m-right-md hidden-xs banner-color">
                                    innovating online digital payment services <br />
                                    and revolutionizing ecommerce
                                </p>
                                <a href="index-2.html" class="btn btn-default btn-lg fadeInLeftLarge animation-delay8 m-bottom-lg m-right-md">Find Out More</a>
                            </div>
                        </div>
                    </div>
                </div>
                <a class="left carousel-control" href="#main-slider" data-slide="prev">
                    <span class="fa fa-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#main-slider" data-slide="next">
                    <span class="fa fa-chevron-right"></span>
                </a>
            </div>
            <div class="bg-white content-padding text-center font-lg">
                <div class="container">
                    <span class="m-right-lg"><h1><b>Cash Location</b></h1></span>
                    <div class="inline-block m-top-sm">
                        <p> Note: This is a sample paragraph only</p>
                        <p style="text-align:justify">
                            <small>
                                Today’s web-savvy customers require self-service banking access to automate recurring bill payments with the convenience and flexibility of making payments anytime and anywhere. With the Coop Red Direct Debit System (DDS), your members can easily and efficiently self-service all aspects of their accounts from anywhere in the world; 24/7 while remaining transparent.

                                The DDS system is a recurring bill payment system whereby service providers and businesses, that have joined the Coop Red Network, can enhance their debt collection and payment process. DDS allows your members to automatically pay bills directly from their account without writing a check or withdrawing cash. Additional, the system allows automatic payments to any business or service provider that has registered with the Coop Red Network. Your members are in full control over when their payments will be made, the amount of payments and all things related to the payment. It can be turned off at any time and then back on at the convenience of the member.

                                DDS also works with business and service providers not registered with the Coop Red Network provided your member has the required banking information for the business or service provider. The DDS system delivers a consistent bill payment experience.

                                DDS provides member merchants with rapid reductions in operational costs, quicker payment turnaround and enhanced customer service
                            </small>
                        </p>
                    </div>
                </div>
            </div>
            <div id="block-nodeblock-4" class="section-lg block block-nodeblock m-top7">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                            <div class="sec-titiel m-bottom5">
                                <h2 class="uppercase font-black font30 nomargin">Exclusive Services</h2>
                            </div>
                            <div class="col-md-12 m-bottom1 nopadding">
                                <div class="content-feature-col one">
                                    <div class="icon-box-col"> <span class="icon-layers"></span> </div>
                                    <div class="feature-icon-col left-padd10">
                                        <h2 class="font-black font20 uppercase m-bottom1">e-Mail Money</h2>
                                        <p>A secure and convenient way to send and receive money directly from one bank account to another.</p>
                                        <div class="title-line wide50 color m-top2"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12 m-bottom1 nopadding">
                                <div class="content-feature-col active one">
                                    <div class="icon-box-col"> <span class="icon-cup"></span> </div>
                                    <div class="feature-icon-col left-padd10">
                                        <h2 class="font-black font20 uppercase m-bottom1">Server to Server Money Transfer</h2>
                                        <p>Faster and cheaper than going through payment instructions via SWIFT.</p>
                                        <div class="title-line wide50 color m-top2"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12 m-bottom1 nopadding">
                                <div class="content-feature-col one">
                                    <div class="icon-box-col"> <span class="icon-call-out"></span> </div>
                                    <div class="feature-icon-col left-padd10">
                                        <h2 class="font-black font20 uppercase m-bottom1">Direct Debit/Deposit</h2>
                                        <p>Allow your customers to pay bills directly from their cooperative account or fund their account from any existing bank accounts..</p>
                                        <div class="title-line wide50 color m-top2"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6"> <img class="img-responsive" alt="" src="http://newdrupal.expertscabin.com/sites/default/files/new/index.png" data-anim-delay="100" data-anim-type="fade-in-left"> </div>
                    </div>
                </div>
            </div>
            <p>&nbsp;</p>
        </div><!-- /landing-content -->

Cooptavanza.Wallet/Views/Services/Check21.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }
       <div id="landing-content">
    <div id="main-slider" class="carousel slide bg-dark" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#main-slider" data-slide-to="0" class="active"></li>
            <li data-target="#main-slider" data-slide-to="1"></li>
        </ol>
        <div class="carousel-inner">
            <div class="item active">
                <img src="https://static.pexels.com/photos/267447/pexels-photo-267447.jpeg" alt="" class="img-background">
                <div class="row">
                    <div class="col-md-6 text-right">
                        <h2 style="" class="m-top-lg m-right-md text-white fadeInDownLarge animation-delay3 banner-font"><b>Check 21</b></h2>
                        <p style="" class="text-white fadeInUpLarge animation-delay6 m-right-md hidden-xs banner-color">
                            innovating online digital payment services <br />
                            and revolutionizing ecommerce
                        </p>
                        <a href="index-2.html" class="btn btn-default btn-lg fadeInLeftLarge animation-delay8 m-bottom-lg m-right-md">Find Out More</a>
                    </div>
                </div>
            </div>
            <div class="item">
                <img src="https://static.pexels.com/photos/267447/pexels-photo-267447.jpeg" alt="" class="img-background">
                <div class="row">
                    <div class="col-xs-6 text-right">
                        <!--<img src="img/coop-card.jpg" alt="responsive" class="fadeInLeftLarge animation-delay6 m-top-lg m-bottom-lg">-->
                    </div>
                    <div class="col-xs-6">
                        <h2 style="" class="m-top-lg m-right-md text-white fadeInDownLarge animation-delay3 banner-font">Check 21</h2>
                        <p style="" class="text-warning fadeInUpLarge animation-delay6 hidden-xs banner-color">
                            Fastest way and effortless <br />
                            to pay your bill
                        </p>
                        @*Login Link*@
                        <a href="@Url.Action(" Index", "Signin" )" class="btn btn-default btn-lg fadeInRightLarge animation-delay8">Login <i class="fa fa-arrow-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <a class="left carousel-control" href="#main-slider" data-slide="prev">
            <span class="fa fa-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#main-slider" data-slide="next">
            <span class="fa fa-chevron-right"></span>
        </a>
    </div>
    <div class="bg-white content-padding text-center font-lg">
        <div class="container">
            <span class="m-right-lg"><h1><b>Check 21</b></h1></span>
            <div class="inline-block m-top-sm">
                <p style="text-align:justify">
                    <small>
                        The Check Clearing for the 21st Century Act (or Check 21 Act) is a United States federal law, Pub.L. 108–100, that was enacted on October 28, 2003 by the 108th U.S. Congress. The Check 21 Act took effect one year later on October 28, 2004. The law allows the recipient of the original paper check to create a digital version of the original check, a process known as check truncation, into an electronic format called a "substitute check", thereby eliminating the need for further handling of the physical document. In essence, the recipient bank no longer returns the paper check, but effectively e-mails an image of both sides of the check to the bank it is drawn upon.

                        Consumers are most likely to see the effects of this act when they notice that certain checks (or image of) are no longer being returned to them with their monthly statement, even though other checks are still being returned. Another effect of the law is that it is now legal for anyone to use a computer scanner or mobile phone to capture images of checks and deposit them electronically, a process known as remote deposit.

                        Check 21 is not subject to ACH (Automated Clearing House) rules, therefore transactions are not subject to NACHA (The Electronic Payments Association) rules, regulations, fees and fines.
                    </small>
                </p>
            </div>
        </div>
    </div>
</div><!-- /landing-content -->

Cooptavanza.Wallet/Views/Services/ChinaRemit.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }
       <div id="landing-content">
    <div id="main-slider" class="carousel slide bg-dark" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#main-slider" data-slide-to="0" class="active"></li>
            <li data-target="#main-slider" data-slide-to="1"></li>
        </ol>
        <div class="carousel-inner">
            <div class="item  active">
                <img src="https://static.pexels.com/photos/265667/pexels-photo-265667.jpeg" alt="" class="img-background">
                <div class="row">
                    <div class="col-xs-6 text-right">
                        <!--<img src="img/coop-card.jpg" alt="responsive" class="fadeInLeftLarge animation-delay6 m-top-lg m-bottom-lg">-->
                    </div>
                    <div class="col-xs-6">
                        <h2 style="" class="m-top-lg m-right-md text-white fadeInDownLarge animation-delay3 banner-font">China Remit</h2>
                        <p style="" class="text-warning fadeInUpLarge animation-delay6 hidden-xs banner-color">
                            Send Money any where in the world
                        </p>
                        <a href="@Url.Action(" Index", "Signin" )" class="btn btn-default btn-lg fadeInRightLarge animation-delay8">Login <i class="fa fa-arrow-right"></i></a>
                    </div>
                </div>
            </div>
            <div class="item">
                <img src="/Content/images/money_transfer_1.2.jpg" alt="" class="img-background">
                <div class="row">
                    <div class="col-md-6 text-right">
                        <h2 style="" class="m-top-lg m-right-md text-white fadeInDownLarge animation-delay3 banner-font"><b>China Remit</b></h2>
                        <p style="" class="text-white fadeInUpLarge animation-delay6 m-right-md hidden-xs banner-color">
                            innovating online digital payment services <br />
                            and revolutionizing ecommerce
                        </p>
                        <a href="index-2.html" class="btn btn-default btn-lg fadeInLeftLarge animation-delay8 m-bottom-lg m-right-md">Find Out More</a>
                    </div>
                </div>
            </div>
        </div>
        <a class="left carousel-control" href="#main-slider" data-slide="prev">
            <span class="fa fa-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#main-slider" data-slide="next">
            <span class="fa fa-chevron-right"></span>
        </a>
    </div>
    <div class="bg-white content-padding text-center font-lg">
        <div class="container">
            <span class="m-right-lg"><h1><b>China Remit</b></h1></span>
            <div class="inline-block m-top-sm">
                <p> Note: This is a sample paragraph only</p>
                <p style="text-align:justify">
                    <small>
                        "Remit to china Top-up UnionPay Cards in 40 Seconds"
                        From abroad remit to UnionPay cardholders throughout China.
                        Secure, quick and easy to use web based MoneyExpress portal
                        Licensed and certified by UnionPay
                        Real time authentication with UnionPay and the State Administration of Foreign Exchange of China (“SAFE”)
                        Online access to transaction, settlement reports and support services
                        "Remit to China in 40 seconds"
                        Real-Time Remittance to UnionPay Cards
                        Real-Time S.A.F.E. Verification
                        Online Access to Reports
                    </small>
                </p>
            </div>
        </div>
    </div>
    <p>&nbsp;</p>
</div><!-- /landing-content -->