Cooptavanza.Wallet/Controllers/ForgetPassController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cooptavanza.Wallet.Controllers
{
    public class ForgetPassController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

      
    }
}

Cooptavanza.Wallet/Controllers/SigninController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cooptavanza.Wallet.Controllers
{
    public class SigninController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
       
    }
}

Cooptavanza.Wallet/Views/Signin/Index.cshtml
@{ Layout = "~/Views/Shared/_LayoutAdmin.cshtml"; }
<div growl class="pull-right"></div>
<div ng-controller="CWLoginController">
<!--Login Page-->
   
<div class="login-wrapper">
    
    <div class="text-center">
        <img src="~/Content/templateFrontend/customerAdmin/img/cw-logo.png" alt="User Avatar" style="padding-left:15em !important;">
        <h2 class="fadeInUp" style="font-weight:bold">
            <span class="text-primary">Coop</span> <span style="color:#afafaf; text-shadow:0 1px #fff">Wallet</span>
        </h2>
    </div>
    <div class="login-widget">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <div class="pull-left">
                    <i class="fa fa-lock fa-lg"></i> Login
                </div>
            </div>
            <div class="panel-body">
                
                <form class="form-login">
                    <div class="form-group">
                        <label>Mobile No.</label>
                        <input type="text" placeholder="Mobile Number" id="mobilenumber" data-ng-keypress="($event.charCode==13)? pressEnter($event) : return" class="form-control input-sm" ng-intl-tel-input ng-model="login.mobilenumber" style="width:366px!important;" ng-change="change()">
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" placeholder="Password" class="form-control input-sm" data-ng-keypress="($event.charCode==13)? pressEnter($event) : return"  ng-model="login.password">
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <div class="col-md-6">
                                <label class="label-checkbox inline">
                                    <input type="checkbox" class="regular-checkbox chk-delete" />
                                    <span class="custom-checkbox info"></span>
                                </label>
                                Remember me
                            </div>
                            <div class="col-md-6" align="right">
                                <a href="@Url.Action("Index", "ForgetPass")">Forget Password?</a>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12" align="left">
                            <span style="font-size:11px;">Don't have an account? </span><a class="btn btn-default btn-xs login-link" href="@Url.Action("Index", "Registration")" style="margin-top:-2px;"> <i class="fa fa-plus-circle"></i> Sign up</a>
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="col-md-12" align="right">
                            <hr />
                            <a class="btn btn-primary btn-sm pull-right" ng-click="submitLogin();" ng-disabled="!login.mobilenumber || !login.password"><i class="fa fa-sign-in"></i> Sign in</a>
                        </div>
                    </div>

                    
                </form>
            </div>
        </div><!-- /panel -->
        <div class="form-group">
            <table align="center">
                <tr>
                    <td>
                        <img src="~/Content/templateFrontend/customerAdmin/img/coopred_logo.png" alt="User Avatar">
                    </td>
                    <td>
                        <img src="~/Content/templateFrontend/customerAdmin/img/coop-resized.jpg" alt="User Avatar">
                    </td>
                    <td>
                        <img src="~/Content/templateFrontend/customerAdmin/img/pci_logo.png" alt="User Avatar" style="max-width: 178px;">
                    </td>
                </tr>
            </table>
        </div>
    </div><!-- /login-widget -->
    <div style="display:none" id="dialog">
        <p>This is the default dialog which is useful for displaying information. The dialog window can be moved, resized and closed with the 'x' icon.</p>
    </div>
</div><!-- /login-wrapper -->
</div>